### ISSUE TITLE
Automatic localization of git and conda during Windows installation

### ISSUE THREAD

**Issue by BobbyCephy** [PetervanLunteren/EcoAssist#10]
Installation on Windows would be easier if git and conda were found automatically. `install.bat` could try to find them with `where git` and `where conda`. If the paths are found, you could be prompted to confirm them or enter other paths. Preferably, you could only be prompted to enter them if they were not found.

**Comment by PetervanLunteren** [comment]
@BobbyCephy Good point. That would make the install easier for users which already have `git` or `conda` added to their `PATH`.

In the coming weeks I'm quite busy and don't think I'll have time to do this. If you feel like contributing to EcoAssist and have some spare time, would you be able to fork and submit a pull request with the adjustments to `install.bat`? That would be great :)

**Comment by PetervanLunteren** [comment]
fixed in PR https://github.com/PetervanLunteren/EcoAssist/pull/11

Thanks!

**Comment by BobbyCephy** [comment]
Please, batch script language is horrible :satisfied:
