### ISSUE TITLE
Apple Silicon (M1) installation not working

### ISSUE THREAD

**Issue by lindsayveazey** [PetervanLunteren/EcoAssist#12]
I've downloaded install.command and opened it with the following command:

```
chmod 755 $HOME/Downloads/install.command
bash $HOME/Downloads/install.command
```

My installation _appears_ to proceed...but then stops after this output:

```
Finding available software
: No such update
No updates are available.
```

Full `install.command` output and `conda info` attached.
I am running python 3.8.16.

[installcommand-output.txt](https://github.com/PetervanLunteren/EcoAssist/files/11672809/installcommand-output.txt)

[conda-info-output.txt](https://github.com/PetervanLunteren/EcoAssist/files/11672811/conda-info-output.txt)

**Comment by PetervanLunteren** [comment]
Hi @lindsayveazey,

There seems to go something wrong with the command line tools update. Not sure what it is, but I think that a manual install of command line tools might fix the issue. See [this link](https://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/) for the steps to do that. If successfully installed, reboot your computer and try installing EcoAssist again.

Please let me know if that solves your issue. If so, I'll adjust the script so that future macOS users won't have the same problem.

**Comment by lindsayveazey** [comment]
Hmm. Well, I updated my OS and python (v. 3.10.10) reinstalled Xcode, hoping this would solve the problem- after multiple restarts, the log is basically the same. So, that didn't fix it. If you have any other suggestions, let me know.
[installcommand-output.txt](https://github.com/PetervanLunteren/EcoAssist/files/11681246/installcommand-output.txt)
[conda-info-output.txt](https://github.com/PetervanLunteren/EcoAssist/files/11681250/conda-info-output.txt)

**Comment by PetervanLunteren** [comment]
Could you try running `install.bat` with [this part](https://github.com/PetervanLunteren/EcoAssist/blob/main/install.command#L114-L128) outcommented? That means that you'll have to right-click `install.bat` and open with notepad. Then place hastags (`#`) in front of the lines 114- 128, like this:

```python
# if [ "$PLATFORM" = "Apple Silicon Mac" ] || [ "$PLATFORM" = "Intel Mac" ]; then
#   os=$(sw_vers -productVersion | awk -F. '{print $1 "." $2}')
#   #removed os version check for command line tools as --history prints following now: "Command Line Tools for Xcode   14.3   01/04/2023, 09:36:08"
#   if softwareupdate --history | grep --silent "Command Line Tools"; then
#       echo 'Command-line tools already installed.' 2>&1 | tee -a "$LOG_FILE"
#   else
#       echo 'Installing Command-line tools...' 2>&1 | tee -a "$LOG_FILE"
#       in_progress=/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
#       touch ${in_progress}
#       product=$(softwareupdate --list | awk "/\* Command Line.*${os}/ { sub(/^   \* /, \"\"); print }")
#       softwareupdate --verbose --install "${product}" || echo 'Installation failed.' 1>&2 && rm ${in_progress} && exit 1
#       rm ${in_progress}
#       echo 'Installation succeeded.' 2>&1 | tee -a "$LOG_FILE"
#   fi
# fi
```

**Comment by lindsayveazey** [comment]
Very happy to report that the above solution works for me (with one comment: you meant to specify `install.command`, not `install.bat`). Thank you!
