### ISSUE TITLE
Exif data lost when visualising bounding boxes. 

### ISSUE THREAD

**Issue by ehallein** [PetervanLunteren/EcoAssist#13]
When bounding boxes are drawn (and probably when cropped) in post-processing, it seems the Exif data is lost. This means the date captured is lost, which is important for some analysis later on.

The issue seems to be that _im_to_vis = cv2.imread(os.path.join(src_dir, file))_ converts the image into a numpy array.

the fix is probably to use an Exif library to copy it from the source to the new image.  

I'm happy to look at doing the fix if you like.

**Comment by agentmorris** [comment]
FYI we hit the same issue in a similar script in the MegaDetector repo... specifically, when separating images into folders based on results, we copy images when bounding boxes aren't being rendered, but when they are, we also read and re-write image data, so we hit this issue.  We solved this issue (along with making a best effort to preserve the original jpeg quality setting) like this:

https://github.com/agentmorris/MegaDetector/blob/main/api/batch_processing/postprocessing/separate_detections_into_folders.py#L385

In that script, we only transfer EXIF metadata; we make no effort to transfer IPTC or XMP metadata.  IPTC and XMP data tend to be less relevant for camera trap stuff, *except* for folks using DigiKam with camtrapR, which [share information using XMP](https://cran.r-project.org/web/packages/camtrapR/vignettes/camtrapr2.pdf).  If EcoAssist (or anyone else) ends up solving this in a way that handles XMP as well, let me know!

**Comment by PetervanLunteren** [comment]
Thanks guys!
