### ISSUE TITLE
failure to create .lnk file

### ISSUE THREAD

**Issue by andrea-petrullo** [PetervanLunteren/EcoAssist#15]
I've run through the installation process a couple of times now and I keep getting the following on Windows 10:

CScript Error: Execution of the Windows Script Host failed. (Access is denied. )
"Created EcoAssist.lnk"

We are seeing the following error during the install but not sure how to resolve it:
ERROR conda.core.link:_execute(745): An error occurred while installing package 'conda-forge::bzip2-1.0.8-h8ffe710_4'.
Rolling back transaction: done

Thanks for any help or guidance you can provide.

**Comment by PetervanLunteren** [comment]
@andrea-petrullo It looks like there are two issues here.
1. The first one probably has to due with your security settings, most likely you anti-virus software ([link](https://www.reddit.com/r/MDT/comments/aqytpo/cscript_error_execution_of_the_windows_script/)). Could it be that some VPN, proxy server, antivirus or other protection software was still enabled during installation? This is a common problem with installs on company machines. 
2. The conda.core.link error looks like some problem with the conda installation. Possibly easy to solve ([link](https://github.com/conda/conda/issues/6078#issuecomment-335343644)), but perhaps it won't even be a problem if we solve issue number 1 first.

**Comment by andrea-petrullo** [comment]
Thank you!  That seems to have been the problem...I was able to download it on my personal laptop by turning the antivirus off.  My work computer has administrative locks on it and I'm still trying to get the antivirus temporarily turned off.
