### ISSUE TITLE
PIL UserWarning: Truncated File Read

### ISSUE THREAD

**Issue by Anujkrishna12** [PetervanLunteren/EcoAssist#19]
![1](https://github.com/PetervanLunteren/EcoAssist/assets/131870111/10c47570-816c-4e0b-8f22-5cef0c78ae96)
Hey, peter I have been getting this error lately while using eco assist can you help me fix this.

**Comment by PetervanLunteren** [comment]
@Anujkrishna12 Looks like there is a problem with a truncated file. Can you test something for me?
* Navigate to your `EcoAssist_files` folder. You can find where it is located [here](https://github.com/PetervanLunteren/EcoAssist#uninstall).
* Open `EcoAssist/EcoAssist_GUI.py` with a text editor like Notepad or Visual Studio Code. 
* Add the following two lines to [line 36](https://github.com/PetervanLunteren/EcoAssist/blob/main/EcoAssist_GUI.py#L36)
```python
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
* Save the file and try again.

**Comment by Anujkrishna12** [comment]
> @Anujkrishna12 Looks like there is a problem with a truncated file. Can you test something for me?
> 
> * Navigate to your `EcoAssist_files` folder. You can find where it is located [here](https://github.com/PetervanLunteren/EcoAssist#uninstall).
> * Open `EcoAssist/EcoAssist_GUI.py` with a text editor like Notepad or Visual Studio Code.
> * Add the following two lines to [line 36](https://github.com/PetervanLunteren/EcoAssist/blob/main/EcoAssist_GUI.py#L36)
> 
> ```python
> from PIL import ImageFile
> ImageFile.LOAD_TRUNCATED_IMAGES = True
> ```
> 
> * Save the file and try again.

![Screenshot 2023-08-04 142209](https://github.com/PetervanLunteren/EcoAssist/assets/131870111/2a7e3463-f89c-4d48-a503-514a938e0971)
Its still showing Model warning error

**Comment by PetervanLunteren** [comment]
Can you try if the same error pops up if you [test your installation](https://github.com/PetervanLunteren/EcoAssist#test-your-installation)?

**Comment by Anujkrishna12** [comment]
> Can you try if the same error pops up if you [test your installation](https://github.com/PetervanLunteren/EcoAssist#test-your-installation)?

No, error did not pop in Test.

**Comment by PetervanLunteren** [comment]
Alright, I'm going to need some more information from you. Please explain to be in detail how you got this error. Which feature did you use? Which model did you run? How can I reproduce the error? Would it be possible for you to send me some images on which this error pops up? If so, you can send it to <contact@pvanlunteren.com>.

**Comment by PetervanLunteren** [comment]
For other users: the images were corrupted and that's why it gave out warnings. `Corrupt JPEG data: premature end of data segment`.
