### ISSUE TITLE
Add Windows Subsystem for Linux as an option in instructions.

### ISSUE THREAD

**Issue by ehallein** [PetervanLunteren/EcoAssist#23]
I was able to install and use EcoAssist in the WSL version 2 running Ubuntu 22.04 with relative ease. It runs well on CPU and theoretically should be able to us the GPU (my windows laptop is no NVidia so I can't test, see the WSL documentation). It solves any issues with permissions as WSL is its own environment.

Steps:
1.  Install WSL **version 2** normally as shown [here ](https://learn.microsoft.com/en-us/windows/wsl/setup/environment#file-storage) and [here](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps).  
2. Open up linux and install EcoAssist as normal. 
3. I had to run sudo apt-get install libgl1 to install the openGL libraries (is this checked in the install script?)
4. run ./.EcoAssist_files/EcoAssist/open.command

Thought this could be useful for some people.

**Comment by PetervanLunteren** [comment]
Perfect, thanks for sharing! I've [added](https://github.com/PetervanLunteren/EcoAssist/blob/main/install.command#L272-L276) the `libgl1` package to the install file. No option to test, but I don't expect there to be trouble.

**Comment by PetervanLunteren** [comment]
I've added this as an option for Windows users: https://github.com/PetervanLunteren/EcoAssist/commit/8fa69152eb668726a3115e8be47aa16e8e1b2126
