### ISSUE TITLE
Cannot specify classes for custom model

### ISSUE THREAD

**Issue by SimonKravis** [PetervanLunteren/EcoAssist#25]
In v 4.2 there does not seem to be any way of entering class names when building a custom model

**Comment by PetervanLunteren** [comment]
If you want to add a new label to the list:

<img width="408" alt="Screenshot 2023-10-19 at 09 41 49" src="https://github.com/PetervanLunteren/EcoAssist/assets/85185478/ce7687d6-9e60-40e5-9380-b308c821a017">

* edit the label
* verify the image
* close annotation window
* reopen annotation window

<img width="408" alt="Screenshot 2023-10-19 at 09 42 51" src="https://github.com/PetervanLunteren/EcoAssist/assets/85185478/611c4bd9-5ad7-42a0-a125-07368bc88c80">

Now you the label should be added to the classes list. I’ll add these steps it to the documentation. 

Feel free to reopen this issue if this doesn't work out for you.
