### ISSUE TITLE
Allow seperate_images() to deal with custom classes

### ISSUE THREAD

**Issue by ehallein** [PetervanLunteren/EcoAssist#3]
What do you think about changing the separate_images() function to call the [megadetector separate_detections_into_folders.py ](https://github.com/microsoft/CameraTraps/blob/main/api/batch_processing/postprocessing/separate_detections_into_folders.py)script instead? The will make it seamless to update when megadetector supports custom classes (Microsoft/cameratraps#321) while also supporting multithreaded processing. Would this be difficult to do? I'm happy to implement it. I assume it would be similar to the produce_json() function.

**Comment by ehallein** [comment]
If it's easier and more functional to edit the code in seperate_images(), the lets do that. I'll change this issues title.

At the moment the json only has class numbers, and my understanding is that we need to pull the name out of the model itself e.g:
```
detector = PTDetector(model_file, force_cpu)
for id in detector.model.names:
    DEFAULT_DETECTOR_LABEL_MAP[id+1] = detector.model.names[id]
```
But maybe Dan is planning on add the classnames to the json as well?

**Comment by PetervanLunteren** [comment]
Thanks for pointing me in the right direction. The updated EcoAssist v3.0 now extracts the label map from custom classes and uses that for postprocessing features so that folder separation, visualisation, cropping and annotation work with these custom classes.
