### ISSUE TITLE
object detection followed by classification vs. just object detection

### ISSUE THREAD

**Issue by valentinitnelav** [PetervanLunteren/EcoAssist#31]
Dear @PetervanLunteren ,

@maxsitt  and I came across your comment for you EcoAssist release -https://github.com/PetervanLunteren/EcoAssist/releases/tag/v4.4 

> In previous versions of EcoAssist (v3.0 > v4.3) it was possible to train your own object detection models based on MegaDetector to detect your target species. Although this did work, it wasn't the best approach to develop a species recognition model. It required lots of training data, processing power, time, electricity and wasn't very accurate. **Advancing insights revealed that better results can be obtained by using a object classification model to be used in conjunction with the results of MegaDetector.** The animals will then be located by MegaDetector, and further classified by your custom model. 

So, if I understand correctly, the way to go ahead involves initially using an object detector, such as YOLO, primarily for localization rather than classification. Subsequently, a separate classifier is applied to the images cropped based on the bounding boxes provided by the object detector. 
My questions are:
- 1) Does this two-step method (object detection followed by classification) demonstrate more efficiency in terms of overall performance compared to using an object detector like YOLO for both localization and classification directly, without an additional classifier? 
- 2) If yes, are you aware of some published work that addressed this (can be from other domains, not only life sciences). I struggle to find something at the moment.

Cheers

**Comment by PetervanLunteren** [comment]
Yes, you are right. When you use an object detection model to localise the animal (in camera-trap-land this is usually [MegaDetector](https://github.com/agentmorris/MegaDetector), a YOLOv5x model), and then classify the cropped detection, you're basically performing feature extraction. This is of course only possible if you have a decent detector.

> Does this two-step method (object detection followed by classification) demonstrate more efficiency in terms of overall performance compared to using an object detector like YOLO for both localisation and classification directly, without an additional classifier?

In my experience, yes. But I haven't empirically tested it, though. I found that training a reliable detector on many different objects (species) has proven quite difficult. You'll need a lot of training images and a lot of processing power. A classifier was a lot easier, see [this project](https://addaxdatascience.com/projects/2023-01-dlc/). A benefit is of course that you remove the background and make the classifier more generic, so it can yield more reliable results over different ecosystems. The inference time, of course, increases, but only with 10% or so (depending on the number of detections and the model sizes).

> If yes, are you aware of some published work that addressed this (can be from other domains, not only life sciences). I struggle to find something at the moment.

Not necessarily work that I know of that compares detector+classifier vs. detector only, but there are many examples of scientists that do it this way. In camera-trap-land this is more-or-less the normal thing to do. All the models below are classifiers to be used in conjunction with a detector which tells them the bbox coordinates.  

- [Automated wildlife image classification: An active learning tool for ecological applications](https://arxiv.org/pdf/2303.15823.pdf)
- [The DeepFaune initiative: a collaborative effort towards the automatic identification of French fauna in camera-trap images](https://www.biorxiv.org/content/biorxiv/early/2022/03/17/2022.03.15.484324.full.pdf)
- [AI4GAmazonRainforest](https://zenodo.org/records/10042023)
- [AI4GOpossum](https://zenodo.org/records/10042023)
- [MegaClassifier](https://github.com/agentmorris/MegaDetector/tree/main/classification)
- [Mbaza](https://github.com/Appsilon/mbaza?tab=readme-ov-file)
- [UNSW-goannas](https://github.com/agentmorris/unsw-goannas)
- [Southwest US v2](https://sandiegozoo.app.box.com/s/9f3xuqldvg9ysaix9c9ug8tdcrmc2eqx/folder/169794550910)
- [Southwest US v3](https://sandiegozoo.app.box.com/s/9f3xuqldvg9ysaix9c9ug8tdcrmc2eqx/folder/188389181940)
- [Kenyan savanna](https://sandiegozoo.app.box.com/s/9f3xuqldvg9ysaix9c9ug8tdcrmc2eqx/folder/196933085878)
- [Amazon Rainforest](https://sandiegozoo.app.box.com/s/9f3xuqldvg9ysaix9c9ug8tdcrmc2eqx/folder/196929943950)
- [Small mammal classifier for Norway](https://zenodo.org/records/7142734)
- [SpSeg models](https://github.com/bhlab/SpSeg?tab=readme-ov-file#spseg-models)

However, I must say that I don't know if this solution always works better. Perhaps in situations where the background is less confusion it wouldn't work that well. 

Hope this helps!
