### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by ggsherman** [PetervanLunteren/EcoAssist#33]
Hi Peter,

I am trying to use EcoAssist on Windows but am facing issues when I first open it. It says successfully installed but when I open it, the window closes almost immediately. If I run it in the cmd line it gives me this.

Path to conda as imported from "C:\Program Files\EcoAssist_files\EcoAssist\logfiles\path_to_conda_installation.txt" is: "E:\miniforge3"
Path to git as imported from "C:\Program Files\EcoAssist_files\EcoAssist\logfiles\path_to_git_installation.txt" is: "C:\Program Files\Git"
Traceback (most recent call last):
  File "EcoAssist\EcoAssist_GUI.py", line 40, in <module>
    from GPSPhoto import gpsphoto
ModuleNotFoundError: No module named 'GPSPhoto'

I then installed gpsphoto 2.2.3 through miniforge3 but there is no change. I've attached session and install logs
[installation_log.txt](https://github.com/PetervanLunteren/EcoAssist/files/14057701/installation_log.txt)
[session_log.txt](https://github.com/PetervanLunteren/EcoAssist/files/14057702/session_log.txt)

**Comment by PetervanLunteren** [comment]
hi @ggsherman, thanks for you complete bug report including log files. When there is a package conflict, 9 times out of 10, it is due to some kind of security software installed on your computer (VPN, proxy, anti-virus). According to your `installation_log.txt`, you installing EcoAssist on a company computer, which tend to be better protected than personal computers. Is there any protection software running on your computer? If so, could you try to reinstall EcoAssist with these switched off? Running the file as admin might also work, if that is possible.

If that isn't an option, it seems that you know your way around CLI and miniforge. You mention that you've tried to install `GPSPhoto` through Miniforge, but have you installed it in `base` or the `ecoassistcondaenv` environment? Try this:

```shell
conda activate ecoassistcondaenv
pip install gpsphoto
```

**Comment by ggsherman** [comment]
Hi Peter,

Unfortunately there are limits to what I can change on the work computer. I may try an install on my personal computer but I was hoping to get it working on the work computer as I connect to it remotely and it allows me to free up my own computer for other work.

In terms of your suggestions I installed it in ecoassistcondaenv: 
That worked for the gpsphoto and a couple of its dependencies however I am now at line 60 where I get this

Traceback (most recent call last):
  File "EcoAssist\EcoAssist_GUI.py", line 61, in <module>
    from visualise_detection.bounding_box import bounding_box as bb
ModuleNotFoundError: No module named 'visualise_detection'

now looking at the file I can see its from a forked repository, however I'm unsure where to find it to install manually.

Thanks for your help on this.

**Comment by PetervanLunteren** [comment]
The fact that it doesn't find the `visualise_detection` module, implies that something is wrong with the `PATH` or `PYTHONPATH` variable. Try running this before opening:

```
set LOCATION_ECOASSIST_FILES=C:\Program Files\EcoAssist_files
set PATH_TO_CONDA_INSTALLATION=E:\miniforge3
set PATH=%PATH%;%LOCATION_ECOASSIST_FILES%
set PATH=%PATH_TO_CONDA_INSTALLATION%\envs\ecoassistcondaenv;%PATH_TO_CONDA_INSTALLATION%\envs\ecoassistcondaenv\lib\python3.8\site-packages;%PATH%
set PYTHONPATH=%LOCATION_ECOASSIST_FILES%;%LOCATION_ECOASSIST_FILES%\cameratraps;%LOCATION_ECOASSIST_FILES%\ai4eutils;%LOCATION_ECOASSIST_FILES%\yolov5;%LOCATION_ECOASSIST_FILES%\EcoAssist;%LOCATION_ECOASSIST_FILES%\labelImg;%PYTHONPATH%
```

But even if that resolves the immediate issue, there will probably be more down the road... I saw that you installed miniforge on your `E:` drive. Does this has a reason? I also saw that you have a second `ecoassistcondaenv` environment in `C:\Users\SHERG8\AppData\Local\anaconda3`. This might interfere with each other. If possible, I would uninstall both of them and try again, but on the `C:` drive.
