### ISSUE TITLE
'cancel_var' is not defined in start_postprocess()

### ISSUE THREAD

**Issue by gimmw** [PetervanLunteren/EcoAssist#35]
Error post-processing video;

    Traceback (most recent call last):
      File "EcoAssist/EcoAssist_GUI.py", line 561, in start_postprocess
	    if vid_json and not cancel_var:
    NameError: name 'cancel_var' is not defined

Seems like cancel_var is being checked there before initialization (which only happens in `process()` ).

Adding `global cancel_var; cancel_var = False` to `start_postprocess()` might resolve this?

**Comment by PetervanLunteren** [comment]
@gimmw Thanks for catching this! It is still a teething problem from adding the simple mode window. Fixed it like you suggested 

https://github.com/PetervanLunteren/EcoAssist/blob/main/EcoAssist_GUI.py#L546
