### ISSUE TITLE
Bundle EchoAssist with python-appimage

### ISSUE THREAD

**Issue by arky** [PetervanLunteren/EcoAssist#36]
It would be useful to bundle ecoassing with [python-appimage](https://github.com/niess/python-appimage) to create an install AppRun file for gnu/Linux operating system. This might drive adoption with easy to install application.

**Comment by PetervanLunteren** [comment]
@arky That looks amazing! Most EcoAssist users are on either Windows (80%) or macOS (15%), and only a very small percentage is on Linux (5%). Would something like this be also available for Windows of macOS?

**Comment by arky** [comment]
Currently Appimage is linux only. 

Packaging for Windows and Mac requires different toolchains such as winsys and homebrew. Additionally you'll need to pay for certificates which costs money. 

So I generally start with gnu/Linux and then explore other operating systems which resources become available.

**Comment by PetervanLunteren** [comment]
That makes sense. If you feel like you want to give it a try and open a PR, be my guest! I can put it on my TODO list, but I'll take some time before its done...

**Comment by arky** [comment]
@PetervanLunteren It is possible to package for multiple platforms using BeeWare Briefcase, however you'll need to refactor the code and organize it as module so it easy to package.

**Comment by PetervanLunteren** [comment]
@arky Thanks for sharing. That is interesting. I've been planning to improve the installation process and this might be very valuable.

**Comment by arky** [comment]
@PetervanLunteren if you move the default code base to `src/ecoassist` you should be able to build with `briefcase run`. 

Here is example `pyproject.toml`

```
# This project was generated with 0.3.17 using template: https://github.com/beeware/briefcase-template@v0.3.17
[tool.briefcase]
project_name = "EcoAssist"
bundle = "com.addaxdatascience.ecoassist"
version = "0.0.1"
url = "https://addaxdatascience.com/ecoassist/"
license = "MIT license"
author = "Peter van Lunteren"
author_email = "peter@addaxdatascience.com"

[tool.briefcase.app.ecoassist]
formal_name = "EcoAssist"
description = "EcoAssist is an application designed to streamline the work of ecologists dealing with camera trap images."
long_description = """More details about the app should go here.
"""
icon = "src/ecoassist/resources/ecoassist"
sources = [
    "src/ecoassist",
]
test_sources = [
    "tests",
]


```

**Comment by PetervanLunteren** [comment]
Thanks!
