### ISSUE TITLE
Move python code to 'src' folder

### ISSUE THREAD

**Issue by arky** [PetervanLunteren/EcoAssist#39]
To aid packaging of the project, it is recommended to move all python code  to  ["src" folder (ref python packaging guide)](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/). Putting the code in this structure and refactored as modules makes it easier to maintain and also port to multiple platforms.

This is require step before considering packaging EcoAssist to multiple platforms. #36

**Comment by PetervanLunteren** [comment]
Thanks for this tip :)
