### ISSUE TITLE
Incomplete installation

### ISSUE THREAD

**Issue by JoejynWan** [PetervanLunteren/EcoAssist#4]
Hi, 

I am trying to use EcoAssist on my Windows desktop but am facing issues with the installation and running of the program. 

I have tried installing with Windows_install_EcoAssist.bat, but the installation terminates just after the downloading of the MegaDetector model (md_v5b) and the cmd prompt closes before any error message (if any) can be displayed/seen. I know that the installation is incomplete because the ecoassistcondaenv had not yet been installed. 

I suspected that it was an issue with Anaconda, and so I removed the code chunk that installs Anaconda (since I already have it installed). This allowed the installation to proceed, although there are still errors popping up in the cmd terminal (please see attached for the full prompts shown on cmd. Installation log is also attached). From what I can gather, the error is `The filename, directory name, or volume label syntax is incorrect`. 

Despite the error, ecoassistcondaenv could be downloaded and installed. However even with this, when I double click on the EcoAssist shortcut in the downloads folder, nothing comes up. Looking at the session log, it seems that EcoAssist closes by itself, although I dont see anything appearing. 

Would be great to figure out what is the issue here. Please do let me know if more details are needed. Thank you so much! 

OS and program versions: 
Windows 11
Python 3.9.16
conda 23.1.0
git version 2.39.2.windows.1

[cmd_prompts.txt](https://github.com/PetervanLunteren/EcoAssist/files/10852156/cmd_prompts.txt)
[installation_log.txt](https://github.com/PetervanLunteren/EcoAssist/files/10852193/installation_log.txt)
[session_log.txt](https://github.com/PetervanLunteren/EcoAssist/files/10852152/session_log.txt)

**Comment by PetervanLunteren** [comment]
Hi Joejyn,

During your installation the `ecoassistcondaenv` is created, but it's not properly populated with packages. Not sure why... there are some error messages but I can't really make much sense out of them. It might have something to do with anti-virus, VPN or other protection software which blocks the download of some software. If that is the case, could you please reinstall the (non-adjusted) Windows_install_EcoAssist.bat with this protection software disabled?

Also, could you post the output of `conda info`?

**Comment by JoejynWan** [comment]
Hi Peter, 

I do not have any VPN/anti-virus on my computer aside from Windows Defender and Firewall. Even after turning these off, the installation process still leads to the same result. 

Please see below for the output of `conda info`. Thanks!

![image](https://user-images.githubusercontent.com/65271133/222034239-92f53f58-091a-4965-9fbf-a744fafae9db.png)

**Comment by PetervanLunteren** [comment]
The problem is that the base environment folder is read-only. Did you by any chance install conda with sudo?

This should help:

* Go to C:\ProgramData\Anaconda3
* Right-click, choose Properties, and uncheck the read-only box
* Go to "Sharing" Tab, click "Share...", choose "joejyn". Make sure the user has both Read and Write access
* Go back to Anaconda, type "conda info", take a look to make sure your base environment is "writable"
* If that’s done, reinstall EcoAssist as you would normally

**Comment by JoejynWan** [comment]
I have changed the folder to writable as per your instructions, but the installation is still being interrupted. Is there anything else I can try?

![image](https://user-images.githubusercontent.com/65271133/222325870-efcb2c06-0f43-4943-99df-b974f271f469.png)

**Comment by JoejynWan** [comment]
Hi Peter, 

I had found the issue, and as you had expected, it could not find the path to my conda installation. I had realised that in the cmd promt (when I commented out the chunk to check if conda had been installed, please see cmd_promts.txt in the first post), it said: 

`"Found path to conda installation: baseenvironment:="`

So somehow, line 384 to 388 was not able to read `conda info` and find/edit the appropriate string to get the correct conda path. As such, I had to comment out those lines and manually set `PATH_TO_ANACONDA` to the correct path. 

However, this alone was not enough. The cmd promt was still closing prematurely right after installing md_v5b. So I had to also comment out the entire chunk that checks if conda has been installed. Please do see the attached install file to see my edits to make it work. 

I am still unsure of what is causing the premature termination of the program, or why it could not find the correct path even after the base environment has been changed to writable. I am more than happy to help you troubleshoot if you have any suggestions!

Thank you so much for your help on this issue! I am going to close this issue, but please feel free to reopen it if you want to troubleshoot this issue with me!

![image](https://user-images.githubusercontent.com/65271133/222333585-7cd0b78d-4711-4e3c-bc60-fb92c2910511.png)
