### ISSUE TITLE
Adopt new GUI toolkit 

### ISSUE THREAD

**Issue by arky** [PetervanLunteren/EcoAssist#40]
Perhaps adopting a python native, GUI toolkit over like [toga](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html) would ideal for providing similar look and feel across multiple platforms. 

Tinkerer still is a viable option just not as flexible as it needs to be bundled across multiple platforms.

**Comment by PetervanLunteren** [comment]
You are probably right. Tkinter might not be the best option, but I started working with it a few years back... Given the fact that everything works on Tkinter now, it will be a huge effort to rewrite the code to another GUI toolkit.
