### ISSUE TITLE
EcoAssist prerequisites management script

### ISSUE THREAD

**Issue by arky** [PetervanLunteren/EcoAssist#41]
Ecoassist has numerous prerequisites which currently downloaded during install. Perhaps it would be a good idea to streamline these multiple install command per platform into a single python prerequisites management script that does installation if anyone of the prerequisites is missing or corrupt. 

Also the script help improve the downloads using concurrency and restarting downloads from partials in low bandwidth environments.

**Comment by PetervanLunteren** [comment]
What do you mean with a single python prerequisites management script? Can you give an example? Do you mean something like this: https://github.com/agentmorris/MegaDetector/blob/main/envs/environment-detector.yml ?
