### ISSUE TITLE
Documentation of EcoAssist prerequisites 

### ISSUE THREAD

**Issue by arky** [PetervanLunteren/EcoAssist#42]
Please update the EcoAssist documentation or README with full list of  prerequisites and their versions. At the moment you'll need to glean this information from reading the install scripts.

**Comment by PetervanLunteren** [comment]
Yes that is true, but EcoAssist is designed for non-coding nature conservationists. Hence I don't think it will be of much added value if those lists were available. You would need to maintain these lists for every platform and silicon chip version.
