### ISSUE TITLE
Documentation of minium requirements to run EcoAssist 

### ISSUE THREAD

**Issue by arky** [PetervanLunteren/EcoAssist#43]
Please update the documentation with minimum software (OS, Harddrive space) and hardware (CPU,GPU, Memory) requirements to install and run EcoAssist. This would help people quickly access whether they would like to adopt running the tool on their hardware or choose a cloud service instead.

**Comment by PetervanLunteren** [comment]
The required software packages are described in the installation webpages. I agree that the minimum harddrive space generally would be nice to know, but I just haven't gotten around to do this. I labeled this as "todo"
