### ISSUE TITLE
Transition to Pytorch-wildlife v1.0

### ISSUE THREAD

**Issue by arky** [PetervanLunteren/EcoAssist#44]
Recommend looking at [Pytorch-wildlife](https://wildlabs.net/discussion/pytorch-wildlife-collaborative-deep-learning-framework-conservation-v10) which builds upon the and improvements to MegaDetectors v5. 

Also helps in ease of installation and packaging 
#39

**Comment by PetervanLunteren** [comment]
Yes, I'm collaborating with PyTorch Wildlife to get their models incorporated into EcoAssist. Thanks for the heads up!
