### ISSUE TITLE
Post processing 

### ISSUE THREAD

**Issue by Anujkrishna12** [PetervanLunteren/EcoAssist#45]
Hello Peter

I am facing this issue recently where during the post process it shows an error where it says one the the file is missing and then it stops processing. Is there any way where I can overlook this error and the post processing doest stop and may be I can fix the issue later looking at the error log file.
![image](https://github.com/PetervanLunteren/EcoAssist/assets/131870111/85974d6f-9341-4bbc-b7a3-19bd4aba295f)

**Comment by PetervanLunteren** [comment]
Hi @Anujkrishna12,

What version of EcoAssist are you running? I just tried to recreate your error and if I delete some images after the analysis and before the post-processing, I get the following warning message.

<img width="372" alt="Screenshot 2024-06-06 at 13 13 56" src="https://github.com/PetervanLunteren/EcoAssist/assets/85185478/5517ec24-3104-4941-bb1e-eb497dfc26cc">

The error log looks like this.

<img width="1370" alt="Screenshot 2024-06-06 at 13 14 20" src="https://github.com/PetervanLunteren/EcoAssist/assets/85185478/7357c610-e0f3-4c74-943d-9053a1cfaf33">

So I believe that updating EcoAssist is the solution to your problem.
