### ISSUE TITLE
Existing tags not transferred to PostProcessing output

### ISSUE THREAD

**Issue by SimonKravis** [PetervanLunteren/EcoAssist#48]
When tags have been applied to data being processed by EcoAssist 5.4 the tags are not transferred to post-processing output

**Comment by SimonKravis** [comment]
Post Processing was using Copy mode

**Comment by SimonKravis** [comment]
Files detected as empty do show tags - adding detection boxes looks as though it removes them

**Comment by PetervanLunteren** [comment]
Hi @SimonKravis,

Can you provide me an step-by-step minimal reproducible example? Please explain the problem, process and expected outcome. Preferably with these [test images](https://github.com/PetervanLunteren/EcoAssist/tree/main/test_images).

Something like:

1. Analyse test_images with MegaDetector 5a and no classification model. 
2. Open human verification.
3. Select all images.
4. add bounding box to image_1.jpg.
5. etc.

Expected outcome: ...
Problem: ...
