### ISSUE TITLE
Image Verification Bug

### ISSUE THREAD

**Issue by Psych0Kitty** [PetervanLunteren/EcoAssist#49]
![image](https://github.com/PetervanLunteren/EcoAssist/assets/115454405/6922ea6f-59fd-4884-843a-2ffea38030d0)
![image](https://github.com/PetervanLunteren/EcoAssist/assets/115454405/3c0df0ee-8c0b-4643-9dac-da567474e526)

Hi there, 

I am having an issue with image verification not processing. In the second image, after pressing the verification button or space bar, it highlights the background yellow but not ticking off in the Files List. No matter how long I wait, it never completes.

Please advise on how this can be fixed. 

Thank you.

**Comment by PetervanLunteren** [comment]
Hi @Psych0Kitty ,

That is weird... There must be something going on in the backend. Could you run EcoAssist in [debug mode](https://github.com/PetervanLunteren/EcoAssist/blob/main/markdown/debug_mode.md) and recreate the error? 

Could you then check the console output for an error message and copy-paste it here? That would guide us in the right direction. 

Cheers,

Peter

**Comment by Psych0Kitty** [comment]
Hi Peter

I ran it in debug mode as you asked and this is what it outputs when I try to verify the image: 

Image:D:\Field Cameras\Likkewaan_24.02.09-24.05.20\Likkewaan_24.02.09-24.05.20  (154).JPG -> Annotation:D:\Field Cameras\Likkewaan_24.02.09-24.05.20\temp-folder\Likkewaan_24.02.09-24.05.xml
Image:D:\Field Cameras\Likkewaan_24.02.09-24.05.20\Likkewaan_24.02.09-24.05.20  (154).JPG -> Annotation:D:\Field Cameras\Likkewaan_24.02.09-24.05.20\temp-folder\Likkewaan_24.02.09-24.05.xml
<EA>-<EA>

**Comment by PetervanLunteren** [comment]
Hi @Psych0Kitty, I don's see any concerning output. Could you update EcoAssist to the latest version and try if that resolves the issue? https://addaxdatascience.com/ecoassist-windows/

If the error persists, could you then please run it in debug mode again, and send me the full console output via emai? peter@addaxdatascience.com

**Comment by PetervanLunteren** [comment]
solved with v5.12
