### ISSUE TITLE
Crash when running 5.8 on windows

### ISSUE THREAD

**Issue by SimonKravis** [PetervanLunteren/EcoAssist#50]
Crash when running NZ Invasives classification model on Windows 11 using GPU - local variable 'elapsed time' referenced before assignment. See attached image when running a classification model as well
![Goanna Error](https://github.com/PetervanLunteren/EcoAssist/assets/8662136/a2e39c3d-e8c5-4957-80b1-3d855106445a)

**Comment by PetervanLunteren** [comment]
Hi @SimonKravis,

That error message is saying that the GPU is out of memory. In other words, it can't handle the workload. Apart from buying new hardware, there are a few things you can do.
1. Increase the paging file size. See [FAQ 6 - point 1](https://github.com/PetervanLunteren/EcoAssist/blob/main/markdown/FAQ.md#faq-6-what-should-i-do-when-i-run-out-ofmemory). Please note that the rest of these FAQs are for model training, so are not necessarily applicable for your situation when deploying an existing model. 
2. Decrease the image size from 1280 to 640 at the 'Use custom image size' option in advanced mode.
3. Select the 'Disable GPU processing' option in advanced mode. Processing will go slow, but at least it won't crash.

**Comment by SimonKravis** [comment]
Neither Decreasing the image size to 640 or disabling the GPU  made any difference.

**Comment by PetervanLunteren** [comment]
I'm afraid this is a hardware problem not realted to EcoAssist. Seems like a bug: https://github.com/tensorflow/tensorflow/issues/55818

**Comment by SimonKravis** [comment]
I fear you are right – EcoAssist 5.2 now terminates without doing anything if I click Start Processing , whereas a while ago it ran OK. 5.8 Runs OK on different machine without a GPU. The GPU reports as OK using the DirectX diagnostic and the fact that EcoAssist doesn’t run on the machine with the GPU  with disable GPU checked indicates the problem lies elsewhere. I’ve tried rebooting – makes no difference. Should I try re-installing conda?

 

Regards

 

Simon Kravis

**Comment by SimonKravis** [comment]
After re-installing MiniForge and installing the latest EcoAssist (5.9) seems to be running OK with the classifier model from Barry Brook.

 

Regards

 

Simon Kravis
