### ISSUE TITLE
Crash when running detection model on Windows using EcoAssist 5.8

### ISSUE THREAD

**Issue by SimonKravis** [PetervanLunteren/EcoAssist#51]
Crash as described below when running model on Windows 11 using GPU
![Error2](https://github.com/PetervanLunteren/EcoAssist/assets/8662136/dcb67ddf-0e95-4d99-bc55-77f443b0399b)

**Comment by PetervanLunteren** [comment]
See my answer for the same issue: https://github.com/PetervanLunteren/EcoAssist/issues/50#issuecomment-2199338101
