### ISSUE TITLE
Model name typo

### ISSUE THREAD

**Issue by ingle** [PetervanLunteren/EcoAssist#52]
"Columbian Amazon - AI for Good Lab, Microsoft"
Should this be spelled "Colombian"?

**Comment by PetervanLunteren** [comment]
Hi @ingle, you’re absolutely right! Thanks for pointing that out.

Currently out of office, but I’ll fix this in a few weeks once I’m back.

**Comment by ingle** [comment]
Thanks! (And also thanks to @cruzbernal for catching this!)

**Comment by PetervanLunteren** [comment]
Fixed with https://github.com/PetervanLunteren/EcoAssist/commit/03258ea330d5032d0b8e246b690b8aa50918c59f

Thanks for catching!
