### ISSUE TITLE
Expecting ',' delimiter

### ISSUE THREAD

**Issue by n-a-gilbert** [PetervanLunteren/EcoAssist#57]
I'm having an issue with EcoAssist; after running the analysis (Step 2), when trying to run the post-processing step (Step 4), I get an error which seems to be referring to the recognition file. The error says it's expecting a ',' delimiter and then gives a traceback (going to try to paste a screenshot below). For what it's worth, this has only happened so far with large batches of photos (10k+). I'm going to try to split into smaller batches and see if it works. But, any ideas of what's happening here / options for troubleshooting? Thanks.

**EDIT**: For what it's worth, splitting into smaller batches worked. So this must be an issue with scalability/number of files?

![image](https://github.com/user-attachments/assets/53d96c29-a8d7-4c6c-8857-428321ba1321)

**Comment by n-a-gilbert** [comment]
Thanks for the response. I've been skipping Step 3; the error message pops up when I click the "Start post-processing" button under Step 4. Splitting into smaller batches (~5-6k run through no problem) is working just fine, so no worries!

**Comment by PetervanLunteren** [comment]
Not sure where the file corruption is coming from. But I guess it was a one-time thing! Good luck!
