### ISSUE TITLE
solving environment hangs

### ISSUE THREAD

**Issue by sergewich** [PetervanLunteren/EcoAssist#8]
Dear Peter, 
For some reason I can't get past the solving environment. It just hangs there. Any idea as to why that might be?
Best,
Serge
![Screenshot (21)](https://github.com/PetervanLunteren/EcoAssist/assets/52251953/f31489a5-1cad-4264-acf6-abd7f454e240)

**Comment by PetervanLunteren** [comment]
Hi @sergewich,

Yes, this is very annoying. It's the installation and compilation of the anaconda base environment. Depending on the hardware, it can take quite some time. However, you only have to go through this process once.

Basically, you have two options. 
* option 1 - Just wait until the environment is completed. This can take up to a few hours. 
* option 2 - Kill the process and install miniforge3 [here](https://github.com/conda-forge/miniforge#miniforge3). Then reinstall EcoAssist and enter the path to the miniforge3 folder when prompted for the conda installation. As miniforge3 is much smaller, it will take much less time to install and solve the environment. 

Anyway, I plan to officially switch to another virtual environment manager which will circumvent these issues. That'll probably be done in a week or two, but in the mean time you can try the options above. Let me know if you need more assistance.

**Comment by sergewich** [comment]
Hi,
Thanks. I just waited and now it is fine.
Best.
Serge
